services:
  db:
    image: 'postgres:latest'
    restart: 'unless-stopped'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${JOURNEY_DATABASE_NAME:-nlw_journey}
      POSTGRES_USER: ${JOURNEY_DATABASE_USER:-j587893}
      POSTGRES_PASSWORD: ${JOURNEY_DATABASE_PSWD:-josnei123}
    volumes:
      - 'db:/var/lib/posgresql/data'
  pgadmin:
    depends_on:
      - 'db'
    image: 'dpage/pgadmin4:latest'
    restart: 'unless-stopped'
    ports:
      - '8081:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${JOURNEY_PGADMIN_EMAIL:-journey@nlw.com}
      PGADMIN_DEFAULT_PASSWORD: ${JOURNEY_PGADMIN_PSWD:-password}
    volumes:
      - 'pgadmin:/var/lib/pgadmin'
  mail:
    image: 'axllent/mailpit:latest'
    restart: 'unless-stopped'
    ports:
      - '1025:1025'
      - '8082:8025'
    environment:
      MP_DATABASE: '/data/mailpit.db'
    volumes:
      - 'mail:/data'
  app:
    depends_on:
      - 'db'
      - 'mail'
    build: '.'
    ports:
      - '8080:8080'
    environment:
      JOURNEY_DATABASE_HOST: 'db'
      JOURNEY_DATABASE_PORT: ${JOURNEY_DATABASE_PORT:-5432}
      JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME:-nlw_journey}
      JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER:-j587893}
      JOURNEY_DATABASE_PSWD: ${JOURNEY_DATABASE_PSWD:-josnei123}

volumes:
  db:
    driver: 'local'
  pgadmin:
    driver: 'local'
  mail:
    driver: 'local'
